#!/bin/sh

set -e

flatpak remote-add --if-not-exists --system appcenter https://flatpak.elementary.io/repo.flatpakrepo
flatpak install --system --noninteractive org.gnome.FileRoller//stable || true

#DEBHELPER#

exit 0
